### ISSUE TITLE
UAAC gem fails to start on Windows: Missing EventMachine C extension

### ISSUE THREAD

**Issue by nathan-alden-inl** [cloudfoundry/cf-uaac#45]
Ruby version: `ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]`
MSYS2 version: `20161025`

I installed Ruby and allowed it to install the RIDK. After that, I ran `gem install cf-uaac`, which appeared to succed. However, I am unable to use the uaac gem:

```
PS > uaac
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.4/rubyeventmachine (L
oadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'

        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cf-uaac-4.0.0/lib/uaa/stub/server.rb:14:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cf-uaac-4.0.0/lib/uaa/cli/token.rb:17:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cf-uaac-4.0.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cf-uaac-4.0.0/lib/uaac_cli.rb:15:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cf-uaac-4.0.0/bin/uaac:17:in `<top (required)>'
        from C:/Ruby24-x64/bin/uaac:23:in `load'
        from C:/Ruby24-x64/bin/uaac:23:in `<main>'
```

**Comment by Greenbones** [comment]
For what it's worth, I ran into this issue as well and downgrading to Ruby 2.3 and re-installing the devkit manually got UAAC working for me. Not a solve, but at least a workaround. Seems to be something with 2.4.

**Comment by drennalls** [comment]
FYI I got things to work by doing `gem install eventmachine --platform ruby`
```
PS C:\Users\drennalls> ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
PS C:\Users\drennalls> uaac --version
UAA client 4.1.0
```

**Comment by nathan-alden-inl** [comment]
Thank you! This worked perfectly.

**Comment by llyer** [comment]
@drennalls thanks ,fixed my problem too!

**Comment by llyer** [comment]
@drennalls 
i got the same problem .but i try the command 
`gem install eventmachine --platform ruby`
but not work,do you know why?

follow is my environment info


![image](https://user-images.githubusercontent.com/16920929/33171509-4c704486-d087-11e7-8e5f-15670b381d17.png)

![image](https://user-images.githubusercontent.com/16920929/33171571-9dd2baf2-d087-11e7-9fb2-2adb4c998fb2.png)

**Comment by sreetummidi** [comment]
Closing. Re-open if you are still facing issues

**Comment by IsaiaSilva** [comment]
This problem always occurs ... No convincing answer yet

**Comment by cbw1243** [comment]
This answer works for me: https://stackoverflow.com/questions/30682575/unable-to-load-the-eventmachine-c-extension-to-use-the-pure-ruby-reactor
